/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitorRequestRouteImport } from './routes/visitor.request'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppVisitRequestsPendingRouteImport } from './routes/_app.visit-requests.pending'
import { Route as AppVisitRequestsApprovedRouteImport } from './routes/_app.visit-requests.approved'
import { Route as AppVisitRequestsIdRouteImport } from './routes/_app.visit-requests.$id'
import { Route as AppUsersCreateRouteImport } from './routes/_app.users.create'
import { Route as AppTrackingLiveInsideRouteImport } from './routes/_app.tracking.live-inside'
import { Route as AppTrackingHistoryRouteImport } from './routes/_app.tracking.history'
import { Route as AppSecurityQrValidateRouteImport } from './routes/_app.security.qr-validate'
import { Route as AppSecurityDashboardRouteImport } from './routes/_app.security.dashboard'
import { Route as AppSecurityCheckOutRouteImport } from './routes/_app.security.check-out'
import { Route as AppSecurityCheckInRouteImport } from './routes/_app.security.check-in'
import { Route as AppReportsHostWiseRouteImport } from './routes/_app.reports.host-wise'
import { Route as AppReportsGateWiseRouteImport } from './routes/_app.reports.gate-wise'
import { Route as AppReportsDailySummaryRouteImport } from './routes/_app.reports.daily-summary'
import { Route as AppHostDashboardRouteImport } from './routes/_app.host.dashboard'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorRequestRoute = VisitorRequestRouteImport.update({
  id: '/visitor/request',
  path: '/visitor/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitRequestsPendingRoute = AppVisitRequestsPendingRouteImport.update({
  id: '/visit-requests/pending',
  path: '/visit-requests/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitRequestsApprovedRoute =
  AppVisitRequestsApprovedRouteImport.update({
    id: '/visit-requests/approved',
    path: '/visit-requests/approved',
    getParentRoute: () => AppRoute,
  } as any)
const AppVisitRequestsIdRoute = AppVisitRequestsIdRouteImport.update({
  id: '/visit-requests/$id',
  path: '/visit-requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersCreateRoute = AppUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingLiveInsideRoute = AppTrackingLiveInsideRouteImport.update({
  id: '/tracking/live-inside',
  path: '/tracking/live-inside',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingHistoryRoute = AppTrackingHistoryRouteImport.update({
  id: '/tracking/history',
  path: '/tracking/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityQrValidateRoute = AppSecurityQrValidateRouteImport.update({
  id: '/security/qr-validate',
  path: '/security/qr-validate',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityDashboardRoute = AppSecurityDashboardRouteImport.update({
  id: '/security/dashboard',
  path: '/security/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityCheckOutRoute = AppSecurityCheckOutRouteImport.update({
  id: '/security/check-out',
  path: '/security/check-out',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityCheckInRoute = AppSecurityCheckInRouteImport.update({
  id: '/security/check-in',
  path: '/security/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsHostWiseRoute = AppReportsHostWiseRouteImport.update({
  id: '/reports/host-wise',
  path: '/reports/host-wise',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsGateWiseRoute = AppReportsGateWiseRouteImport.update({
  id: '/reports/gate-wise',
  path: '/reports/gate-wise',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsDailySummaryRoute = AppReportsDailySummaryRouteImport.update({
  id: '/reports/daily-summary',
  path: '/reports/daily-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppHostDashboardRoute = AppHostDashboardRouteImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/visitor/request': typeof VisitorRequestRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/host/dashboard': typeof AppHostDashboardRoute
  '/reports/daily-summary': typeof AppReportsDailySummaryRoute
  '/reports/gate-wise': typeof AppReportsGateWiseRoute
  '/reports/host-wise': typeof AppReportsHostWiseRoute
  '/security/check-in': typeof AppSecurityCheckInRoute
  '/security/check-out': typeof AppSecurityCheckOutRoute
  '/security/dashboard': typeof AppSecurityDashboardRoute
  '/security/qr-validate': typeof AppSecurityQrValidateRoute
  '/tracking/history': typeof AppTrackingHistoryRoute
  '/tracking/live-inside': typeof AppTrackingLiveInsideRoute
  '/users/create': typeof AppUsersCreateRoute
  '/visit-requests/$id': typeof AppVisitRequestsIdRoute
  '/visit-requests/approved': typeof AppVisitRequestsApprovedRoute
  '/visit-requests/pending': typeof AppVisitRequestsPendingRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/visitor/request': typeof VisitorRequestRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/host/dashboard': typeof AppHostDashboardRoute
  '/reports/daily-summary': typeof AppReportsDailySummaryRoute
  '/reports/gate-wise': typeof AppReportsGateWiseRoute
  '/reports/host-wise': typeof AppReportsHostWiseRoute
  '/security/check-in': typeof AppSecurityCheckInRoute
  '/security/check-out': typeof AppSecurityCheckOutRoute
  '/security/dashboard': typeof AppSecurityDashboardRoute
  '/security/qr-validate': typeof AppSecurityQrValidateRoute
  '/tracking/history': typeof AppTrackingHistoryRoute
  '/tracking/live-inside': typeof AppTrackingLiveInsideRoute
  '/users/create': typeof AppUsersCreateRoute
  '/visit-requests/$id': typeof AppVisitRequestsIdRoute
  '/visit-requests/approved': typeof AppVisitRequestsApprovedRoute
  '/visit-requests/pending': typeof AppVisitRequestsPendingRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/visitor/request': typeof VisitorRequestRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/host/dashboard': typeof AppHostDashboardRoute
  '/_app/reports/daily-summary': typeof AppReportsDailySummaryRoute
  '/_app/reports/gate-wise': typeof AppReportsGateWiseRoute
  '/_app/reports/host-wise': typeof AppReportsHostWiseRoute
  '/_app/security/check-in': typeof AppSecurityCheckInRoute
  '/_app/security/check-out': typeof AppSecurityCheckOutRoute
  '/_app/security/dashboard': typeof AppSecurityDashboardRoute
  '/_app/security/qr-validate': typeof AppSecurityQrValidateRoute
  '/_app/tracking/history': typeof AppTrackingHistoryRoute
  '/_app/tracking/live-inside': typeof AppTrackingLiveInsideRoute
  '/_app/users/create': typeof AppUsersCreateRoute
  '/_app/visit-requests/$id': typeof AppVisitRequestsIdRoute
  '/_app/visit-requests/approved': typeof AppVisitRequestsApprovedRoute
  '/_app/visit-requests/pending': typeof AppVisitRequestsPendingRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/visitor/request'
    | '/admin/dashboard'
    | '/host/dashboard'
    | '/reports/daily-summary'
    | '/reports/gate-wise'
    | '/reports/host-wise'
    | '/security/check-in'
    | '/security/check-out'
    | '/security/dashboard'
    | '/security/qr-validate'
    | '/tracking/history'
    | '/tracking/live-inside'
    | '/users/create'
    | '/visit-requests/$id'
    | '/visit-requests/approved'
    | '/visit-requests/pending'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/visitor/request'
    | '/admin/dashboard'
    | '/host/dashboard'
    | '/reports/daily-summary'
    | '/reports/gate-wise'
    | '/reports/host-wise'
    | '/security/check-in'
    | '/security/check-out'
    | '/security/dashboard'
    | '/security/qr-validate'
    | '/tracking/history'
    | '/tracking/live-inside'
    | '/users/create'
    | '/visit-requests/$id'
    | '/visit-requests/approved'
    | '/visit-requests/pending'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/visitor/request'
    | '/_app/admin/dashboard'
    | '/_app/host/dashboard'
    | '/_app/reports/daily-summary'
    | '/_app/reports/gate-wise'
    | '/_app/reports/host-wise'
    | '/_app/security/check-in'
    | '/_app/security/check-out'
    | '/_app/security/dashboard'
    | '/_app/security/qr-validate'
    | '/_app/tracking/history'
    | '/_app/tracking/live-inside'
    | '/_app/users/create'
    | '/_app/visit-requests/$id'
    | '/_app/visit-requests/approved'
    | '/_app/visit-requests/pending'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  VisitorRequestRoute: typeof VisitorRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor/request': {
      id: '/visitor/request'
      path: '/visitor/request'
      fullPath: '/visitor/request'
      preLoaderRoute: typeof VisitorRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit-requests/pending': {
      id: '/_app/visit-requests/pending'
      path: '/visit-requests/pending'
      fullPath: '/visit-requests/pending'
      preLoaderRoute: typeof AppVisitRequestsPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit-requests/approved': {
      id: '/_app/visit-requests/approved'
      path: '/visit-requests/approved'
      fullPath: '/visit-requests/approved'
      preLoaderRoute: typeof AppVisitRequestsApprovedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit-requests/$id': {
      id: '/_app/visit-requests/$id'
      path: '/visit-requests/$id'
      fullPath: '/visit-requests/$id'
      preLoaderRoute: typeof AppVisitRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/create': {
      id: '/_app/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AppUsersCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/live-inside': {
      id: '/_app/tracking/live-inside'
      path: '/tracking/live-inside'
      fullPath: '/tracking/live-inside'
      preLoaderRoute: typeof AppTrackingLiveInsideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/history': {
      id: '/_app/tracking/history'
      path: '/tracking/history'
      fullPath: '/tracking/history'
      preLoaderRoute: typeof AppTrackingHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/qr-validate': {
      id: '/_app/security/qr-validate'
      path: '/security/qr-validate'
      fullPath: '/security/qr-validate'
      preLoaderRoute: typeof AppSecurityQrValidateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/dashboard': {
      id: '/_app/security/dashboard'
      path: '/security/dashboard'
      fullPath: '/security/dashboard'
      preLoaderRoute: typeof AppSecurityDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/check-out': {
      id: '/_app/security/check-out'
      path: '/security/check-out'
      fullPath: '/security/check-out'
      preLoaderRoute: typeof AppSecurityCheckOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security/check-in': {
      id: '/_app/security/check-in'
      path: '/security/check-in'
      fullPath: '/security/check-in'
      preLoaderRoute: typeof AppSecurityCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/host-wise': {
      id: '/_app/reports/host-wise'
      path: '/reports/host-wise'
      fullPath: '/reports/host-wise'
      preLoaderRoute: typeof AppReportsHostWiseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/gate-wise': {
      id: '/_app/reports/gate-wise'
      path: '/reports/gate-wise'
      fullPath: '/reports/gate-wise'
      preLoaderRoute: typeof AppReportsGateWiseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/daily-summary': {
      id: '/_app/reports/daily-summary'
      path: '/reports/daily-summary'
      fullPath: '/reports/daily-summary'
      preLoaderRoute: typeof AppReportsDailySummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/host/dashboard': {
      id: '/_app/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof AppHostDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppHostDashboardRoute: typeof AppHostDashboardRoute
  AppReportsDailySummaryRoute: typeof AppReportsDailySummaryRoute
  AppReportsGateWiseRoute: typeof AppReportsGateWiseRoute
  AppReportsHostWiseRoute: typeof AppReportsHostWiseRoute
  AppSecurityCheckInRoute: typeof AppSecurityCheckInRoute
  AppSecurityCheckOutRoute: typeof AppSecurityCheckOutRoute
  AppSecurityDashboardRoute: typeof AppSecurityDashboardRoute
  AppSecurityQrValidateRoute: typeof AppSecurityQrValidateRoute
  AppTrackingHistoryRoute: typeof AppTrackingHistoryRoute
  AppTrackingLiveInsideRoute: typeof AppTrackingLiveInsideRoute
  AppUsersCreateRoute: typeof AppUsersCreateRoute
  AppVisitRequestsIdRoute: typeof AppVisitRequestsIdRoute
  AppVisitRequestsApprovedRoute: typeof AppVisitRequestsApprovedRoute
  AppVisitRequestsPendingRoute: typeof AppVisitRequestsPendingRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppHostDashboardRoute: AppHostDashboardRoute,
  AppReportsDailySummaryRoute: AppReportsDailySummaryRoute,
  AppReportsGateWiseRoute: AppReportsGateWiseRoute,
  AppReportsHostWiseRoute: AppReportsHostWiseRoute,
  AppSecurityCheckInRoute: AppSecurityCheckInRoute,
  AppSecurityCheckOutRoute: AppSecurityCheckOutRoute,
  AppSecurityDashboardRoute: AppSecurityDashboardRoute,
  AppSecurityQrValidateRoute: AppSecurityQrValidateRoute,
  AppTrackingHistoryRoute: AppTrackingHistoryRoute,
  AppTrackingLiveInsideRoute: AppTrackingLiveInsideRoute,
  AppUsersCreateRoute: AppUsersCreateRoute,
  AppVisitRequestsIdRoute: AppVisitRequestsIdRoute,
  AppVisitRequestsApprovedRoute: AppVisitRequestsApprovedRoute,
  AppVisitRequestsPendingRoute: AppVisitRequestsPendingRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  VisitorRequestRoute: VisitorRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
